// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iktyptdrlkvymagezsyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrdHlwdGRybGt2eW1hZ2V6c3lyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5OTIxNTYsImV4cCI6MjA2NzU2ODE1Nn0.ThZcRkTtpk2wfOtMXRXLgiawnRUlwdF_wFWqapiBk4M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});